on:
  push:
  pull_request:
jobs:
  macos:
    runs-on: macos-latest
    env:
      LDFLAGS: -L/usr/local/opt/openblas/lib
      CPPFLAGS: -I/usr/local/opt/openblas/include
    steps:
    - uses: actions/checkout@v4
    - run: brew remove go@1.20 openssl@1.1 packer
    - run: brew untap homebrew/cask
    - run: brew untap homebrew/core
    - run: brew cleanup
    - run: brew config
    - run: brew doctor
    - run: brew update
    - run: brew install dlib
    - run: cat /usr/local/Cellar/dlib/19.24.2/lib/cmake/dlib/dlib.cmake
    #- run: |
        #git clone -b v19.24.2 https://github.com/davisking/dlib.git
        #cmake -B dlib/build -DDLIB_USE_BLAS=ON -DDLIB_USE_LAPACK=ON -DDLIB_NO_GUI_SUPPORT=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/tmp/install dlib
        #cmake --build dlib/build --target install --parallel 3
    #- run: cat /tmp/install/lib/cmake/dlib/dlib.cmake
    #- run: diff -ur /usr/local/Cellar/dlib/19.24.2/lib/cmake/dlib/dlib.cmake /tmp/install/lib/cmake/dlib/dlib.cmake
    #- run: sed -i .bak "s|/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include||g" /usr/local/Cellar/dlib/19.24.2/lib/cmake/dlib/dlib.cmake
    - run: |
        cmake -B build -DCMAKE_VERBOSE_MAKEFILE=ON .
        cmake --build build

  macos2:
    runs-on: macos-latest
    env:
      LDFLAGS: -L/usr/local/opt/openblas/lib
      CPPFLAGS: -I/usr/local/opt/openblas/include
    steps:
    - uses: actions/checkout@v4
    - run: brew update
    - run: brew install dlib --force
    #- run: brew upgrade
    #- run: sed -i .bak "s|/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include||g" /usr/local/Cellar/dlib/19.24.2/lib/cmake/dlib/dlib.cmake
    - run: |
        cmake -B build -DCMAKE_VERBOSE_MAKEFILE=ON .
        cmake --build build
